
const arrayData = [
  {
    id: 'ind1',
    name: 'Indicator 1',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '1',
    group: ['costo'],
  },
  {
    id: 'ind2',
    name: 'Indicator 2',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '2',
    group: ['riesgo'],
  },
  {
    id: 'ind3',
    name: 'Indicator 3',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '3',
    group: ['costo', 'monitoreo'],
  },
  {
    id: 'ind4',
    name: 'Indicator 4',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '1',
    group: ['riesgo', 'monitoreo'],
  },
  {
    id: 'ind5',
    name: 'Indicator 5',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '3',
    group: ['riesgo', 'costo', 'oportunidad'],
  },
  {
    id: 'ind6',
    name: 'Indicator 6',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '2',
    group: ['riesgo', 'costo', 'oportunidad', 'monitoreo', 'bioma'],
  },
  {
    id: 'ind7',
    name: 'Indicator 7',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '2',
    group: ['monitoreo', 'costo'],
  },
  {
    id: 'ind8',
    name: 'Indicator 8',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '1',
    group: ['riesgo', 'bioma'],
  },
  {
    id: 'ind9',
    name: 'Indicator 9',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '1',
    group: ['bioma', 'monitoreo', 'oportunidad'],
  },
  {
    id: 'ind10',
    name: 'Indicator 10',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '2',
    group: ['riesgo', 'bioma', 'monitoreo', 'oportunidad'],
  },
  {
    id: 'ind11',
    name: 'Indicator 11',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '1',
    group: ['monitoreo', 'oportunidad'],
  },
];

export { arrayData as default };
