
const arrayData = [
  {
    id: 'ind1',
    name: 'Indicator 1',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '1',
    class: 'riesgo',
  },
  {
    id: 'ind2',
    name: 'Indicator 2',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '2',
    class: 'costo',
  },
  {
    id: 'ind3',
    name: 'Indicator 3',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '3',
    class: 'oportunidad',
  },
  {
    id: 'ind4',
    name: 'Indicator 4',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '1',
    class: 'monitoreo',
  },
  {
    id: 'ind5',
    name: 'Indicator 5',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '1',
    class: 'bioma',
  },
  {
    id: 'ind6',
    name: 'Indicator 6',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '2',
    class: 'costo',
  },
  {
    id: 'ind7',
    name: 'Indicator 7',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '2',
    class: 'bioma',
  },
  {
    id: 'ind8',
    name: 'Indicator 8',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '3',
    class: 'riesgo',
  },
  {
    id: 'ind9',
    name: 'Indicator 9',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '1',
    class: 'oportunidad',
  },
  {
    id: 'ind10',
    name: 'Indicator 10',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '3',
    class: 'monitoreo',
  },
  {
    id: 'ind11',
    name: 'Indicator 10',
    sedimentaryBasin: 'Llanos Orientales',
    rating: 'EXPLOTACIÓN',
    type: '1',
    class: 'monitoreo',
  },
];

export { arrayData };
